### ISSUE TITLE
Discussion: Use HTMLRewriter to include the websocket connection script

### ISSUE THREAD

**Issue by gtrabanco** [aabccd021/bun-html-live-reload#2]
Would not be better use native Bun HTMLRewriter to modify the html file?
Will you write this code as Elyisia or similar Framework plugin?

**Comment by aabccd021** [comment]
I have no future plan for using HTMLRewriter as current code works fine with me.
Having said that, I will happily accept a PR implementing it if anyone made one.
Also I don't have any plan for framework specific implementation for now.
